[project]
name = "presslake"
version = "0.1.0"
description = "Datalake presse (RSS) puis RAG sourcé"
readme = "README.md"
authors = [
    { name = "anthony-marais", email = "67336192+anthony-marais@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.43.83",
    "feedparser>=6.0.14",
    "httpx>=0.28.1",
    "psycopg[binary]>=3.3.4",
    "python-dotenv>=1.2.3",
    "pyyaml>=6.0.3",
]

[project.scripts]
presslake = "presslake:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
]
